version: '3'
services:
  neo4j:
    image: neo4j:4.3.1
    container_name: neo4j
    user: root
    volumes:
      - ./data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
      - TZ=Asia/Shanghai

networks:
  default: